# Federation service provided by StellarID.io
FEDERATION_SERVER="https://stellarid.io/federation/"

ACCOUNTS=[
"GAH35Z7SMOCK4HJKWY5UFXC7HJGU6IV7GBR6TOIVZA3KPYQ5IRKOBALT",
"GBSXDLGP5YN6X6EJ33QP6UTZLTCH7UCLIU7LZKGMXZUQOFZB6HISSUER",
"GCIYSLCHO7GR7I3XPJE4UCIVTBWJB3TGAA4MB4VV3PRU5XCBVYVAULTY",
"GCOQZW3GLBAUDK2Z2WOMC4ILSLMHGP6CFFNYWZMAI6CAEBSNITVAULTX",
"GBAADZXNMQKSOS7QKKWDRMRDXEC7BRW3DGRFERFN7QITCT7TAEVAULTZ",
"GBYXWZ5AHNADRK7YNSM7PYTGRJPZ6XK6KS5AZB4S7XM6XS6WEBSIGNER",
"GDHXY6Z2RURKC5WHLIERN5AYJUQIITU7PMSFLBATVHJB3KLLNMZ5NT4M",
"GDZBISTVV4O7F2ANI5YIPKC46BE6ATMBFY5G45RJG5PWHZVQNM3MKYHI",
"GD3Q36QSV5DMK27WP7BYCQBYARDFXLR4V6YBQWYXLNIA2CR35ORRIFOE",
"GB22COY7JD2BTLMYTGRFD4X5EX2WLQD5QCFZAG4FQKP5FUMGBH24PPWZ",
"GDXF4DWWJOKV7SAIT6KWOC3KI6ZMUUCZ5P4CIJB5OLD2P2FSL6HSBXET",
"GDU27QWSPU4VQ3DPXFGJMPGMWBXMR46DJJTOMNOTWBYVOJWG2O5GEHXY",
"GANQAKN5MXLYBSYLKTMMERFUCRUVSR4S6OSKCAQ5YJ6ZJWXUPT7MBJUQ",
"GDRGL2RANZCUAE4MIJ3AOEDCWZJZTQRMI535VFT5QMB26AISQYJH5YUV",
"GCTYQOK4COD3Q7D7LVOV4CVBA37OKEWJLRQAS3E7MSTHX7XMVYS7BYCN",
"GBQIR3NL42SQ5WIOEM72BWSEWCRQ3YFAMCAOMYQZ3XSUATFQD2CML3PL"
]



[DOCUMENTATION]
ORG_NAME="Thomas R. Brown, W4XZR"
ORG_URL="https://w4xzr.xyz"
ORG_DESCRIPTION="TestNet assets are issued to test and for play by W4XZR"


[[CURRENCIES]]
code="xzrUSD"
issuer="GBSXDLGP5YN6X6EJ33QP6UTZLTCH7UCLIU7LZKGMXZUQOFZB6HISSUER"
display_decimals=7
desc="TestNet assets are issued to test and for play by W4XZR"
image="https://w4xzr.xyz/drawing-2.png"

[[CURRENCIES]]
code="xzrBTC"
issuer="GBSXDLGP5YN6X6EJ33QP6UTZLTCH7UCLIU7LZKGMXZUQOFZB6HISSUER"
display_decimals=7
desc="TestNet assets are issued to test and for play by W4XZR"
image="https://w4xzr.xyz/drawing-2.png"

[[CURRENCIES]]
code="xzrEUR"
issuer="GBSXDLGP5YN6X6EJ33QP6UTZLTCH7UCLIU7LZKGMXZUQOFZB6HISSUER"
display_decimals=7
desc="TestNet assets are issued to test and for play by W4XZR"
image="https://w4xzr.xyz/drawing-2.png"

[[CURRENCIES]]
code="xzrUSDC"
issuer="GBSXDLGP5YN6X6EJ33QP6UTZLTCH7UCLIU7LZKGMXZUQOFZB6HISSUER"
display_decimals=7
desc="TestNet assets are issued to test and for play by W4XZR"
image="https://w4xzr.xyz/drawing-2.png"

[[CURRENCIES]]
code="xzrPAX"
issuer="GBSXDLGP5YN6X6EJ33QP6UTZLTCH7UCLIU7LZKGMXZUQOFZB6HISSUER"
display_decimals=7
desc="TestNet assets are issued to test and for play by W4XZR"
image="https://w4xzr.xyz/drawing-2.png"

[[CURRENCIES]]
code="xzrBNB"
issuer="GBSXDLGP5YN6X6EJ33QP6UTZLTCH7UCLIU7LZKGMXZUQOFZB6HISSUER"
display_decimals=7
desc="TestNet assets are issued to test and for play by W4XZR"
image="https://w4xzr.xyz/drawing-2.png"

[[CURRENCIES]]
code="xzrUSDT"
issuer="GBSXDLGP5YN6X6EJ33QP6UTZLTCH7UCLIU7LZKGMXZUQOFZB6HISSUER"
display_decimals=7
desc="TestNet assets are issued to test and for play by W4XZR"
image="https://w4xzr.xyz/drawing-2.png"

[[CURRENCIES]]
code="xzrTRY"
issuer="GBSXDLGP5YN6X6EJ33QP6UTZLTCH7UCLIU7LZKGMXZUQOFZB6HISSUER"
display_decimals=7
desc="TestNet assets are issued to test and for play by W4XZR"
image="https://w4xzr.xyz/drawing-2.png"

[[CURRENCIES]]
code="xzrETH"
issuer="GBSXDLGP5YN6X6EJ33QP6UTZLTCH7UCLIU7LZKGMXZUQOFZB6HISSUER"
display_decimals=7
desc="TestNet assets are issued to test and for play by W4XZR"
image="https://w4xzr.xyz/drawing-2.png"

[[CURRENCIES]]
code="xzrBUSD"
issuer="GBSXDLGP5YN6X6EJ33QP6UTZLTCH7UCLIU7LZKGMXZUQOFZB6HISSUER"
display_decimals=7
desc="TestNet assets are issued to test and for play by W4XZR"
image="https://w4xzr.xyz/drawing-2.png"
