# Federation service provided by StellarID.io
FEDERATION_SERVER="https://stellarid.io/federation/"

ACCOUNTS=[
"GAH35Z7SMOCK4HJKWY5UFXC7HJGU6IV7GBR6TOIVZA3KPYQ5IRKOBALT",
"GBSXDLGP5YN6X6EJ33QP6UTZLTCH7UCLIU7LZKGMXZUQOFZB6HISSUER",
"GCIYSLCHO7GR7I3XPJE4UCIVTBWJB3TGAA4MB4VV3PRU5XCBVYVAULTY",
"GCOQZW3GLBAUDK2Z2WOMC4ILSLMHGP6CFFNYWZMAI6CAEBSNITVAULTX",
"GBAADZXNMQKSOS7QKKWDRMRDXEC7BRW3DGRFERFN7QITCT7TAEVAULTZ",
"GBYXWZ5AHNADRK7YNSM7PYTGRJPZ6XK6KS5AZB4S7XM6XS6WEBSIGNER"
]

[DOCUMENTATION]
ORG_NAME="Thomas R. Brown, W4XZR"
ORG_URL="https://w4xzr.xyz"
ORG_DESCRIPTION="TestNet assets are issued to test and for play by W4XZR"


[[CURRENCIES]]
code="xzrUSD"
issuer="GBSXDLGP5YN6X6EJ33QP6UTZLTCH7UCLIU7LZKGMXZUQOFZB6HISSUER"
display_decimals=7
desc="TestNet assets are issued to test and for play by W4XZR"

[[CURRENCIES]]
code="xzrBTC"
issuer="GBSXDLGP5YN6X6EJ33QP6UTZLTCH7UCLIU7LZKGMXZUQOFZB6HISSUER"
display_decimals=7
desc="TestNet assets are issued to test and for play by W4XZR"

[[CURRENCIES]]
code="xzrEUR"
issuer="GBSXDLGP5YN6X6EJ33QP6UTZLTCH7UCLIU7LZKGMXZUQOFZB6HISSUER"
display_decimals=7
desc="TestNet assets are issued to test and for play by W4XZR"

[[CURRENCIES]]
code="xzrUSDC"
issuer="GBSXDLGP5YN6X6EJ33QP6UTZLTCH7UCLIU7LZKGMXZUQOFZB6HISSUER"
display_decimals=7
desc="TestNet assets are issued to test and for play by W4XZR"

[[CURRENCIES]]
code="xzrPAX"
issuer="GBSXDLGP5YN6X6EJ33QP6UTZLTCH7UCLIU7LZKGMXZUQOFZB6HISSUER"
display_decimals=7
desc="TestNet assets are issued to test and for play by W4XZR"

[[CURRENCIES]]
code="xzrBNB"
issuer="GBSXDLGP5YN6X6EJ33QP6UTZLTCH7UCLIU7LZKGMXZUQOFZB6HISSUER"
display_decimals=7
desc="TestNet assets are issued to test and for play by W4XZR"

[[CURRENCIES]]
code="xzrUSDT"
issuer="GBSXDLGP5YN6X6EJ33QP6UTZLTCH7UCLIU7LZKGMXZUQOFZB6HISSUER"
display_decimals=7
desc="TestNet assets are issued to test and for play by W4XZR"

[[CURRENCIES]]
code="xzrTRY"
issuer="GBSXDLGP5YN6X6EJ33QP6UTZLTCH7UCLIU7LZKGMXZUQOFZB6HISSUER"
display_decimals=7
desc="TestNet assets are issued to test and for play by W4XZR"

[[CURRENCIES]]
code="xzrETH"
issuer="GBSXDLGP5YN6X6EJ33QP6UTZLTCH7UCLIU7LZKGMXZUQOFZB6HISSUER"
display_decimals=7
desc="TestNet assets are issued to test and for play by W4XZR"

[[CURRENCIES]]
code="xzrBUSD"
issuer="GBSXDLGP5YN6X6EJ33QP6UTZLTCH7UCLIU7LZKGMXZUQOFZB6HISSUER"
display_decimals=7
desc="TestNet assets are issued to test and for play by W4XZR"
